# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dictionary.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dictionary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64ictionary.proto\x12\ndictionary\"\x1b\n\x0bWordRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\"S\n\tWordReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12$\n\x05words\x18\x03 \x03(\x0b\x32\x15.dictionary.WordCount\"(\n\tWordCount\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x32H\n\nDictionary\x12:\n\x08SendWord\x12\x17.dictionary.WordRequest\x1a\x15.dictionary.WordReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dictionary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDREQUEST']._serialized_start=32
  _globals['_WORDREQUEST']._serialized_end=59
  _globals['_WORDREPLY']._serialized_start=61
  _globals['_WORDREPLY']._serialized_end=144
  _globals['_WORDCOUNT']._serialized_start=146
  _globals['_WORDCOUNT']._serialized_end=186
  _globals['_DICTIONARY']._serialized_start=188
  _globals['_DICTIONARY']._serialized_end=260
# @@protoc_insertion_point(module_scope)
